### ISSUE TITLE
macOS 13: Toolbar items not visible, breakpoint window size multiple times wider than screen

### ISSUE THREAD

**Issue by cameroncooke** [ProxymanApp/Proxyman#1256]
I'm having some major issues with the windowing and toolbar interfaces when running on the macOS 13 developer beta 1. I have toolbar set to "Icon & Text" and all my icons are being overflowed (chevron).

Also some windows that are presented automatically, i.e. when hitting a breakpoint are multiple times wider than the screen resolution making it almost impossible to use.

I have not noticed issues like this with other 3rd party software so far.

### Proxyman version? (Ex. Proxyman 1.4.3)

Version 3.5.2 (30520)

### macOS Version? (Ex. mac 10.14)

macOS 13.0 Beta (22A5266r) (aka Ventura) - Developer Beta 1 

### Steps to reproduce 

1. Install macOS Ventura Developer Beta 1
2. Set toolbar to "Icon & Text"
3. Enable breakpoints
4. Trigger breakpoint

### Expected behavior

Toolbar items to be visible unless they actually overlow.
Window sizing to be within the bounds of the screen.

It appears maybe in both cases that the screen size logic might be incorrect causing both icons to overflow and windows to be too wide.

### Screenshots (optional)

<img width="1902" alt="Screenshot 2022-06-16 at 12 49 32" src="https://user-images.githubusercontent.com/630601/174063870-aa89dc71-292c-4ce9-b8c7-b3f67c58f267.png">

<img width="2555" alt="Screenshot 2022-06-16 at 12 51 00" src="https://user-images.githubusercontent.com/630601/174063852-22fec6be-664a-469f-b7b1-22668db0d8e3.png">

**Comment by NghiaTranUIT** [comment]
Thanks for the report @cameroncooke. Some UI is broken on the Beta Ventura 👍 

Regarding the Breakpoint layout issue, you can try this beta build: https://github.com/ProxymanApp/Proxyman/issues/739#issuecomment-1154626111

It's the folder rule, but I also fix the Breakpoint Layout too. I suppose that it should be fixed.

If the toolbar doesn't fix, you can try the `safe` Factory Reset in this Beta build (Help Menu -> Advanced -> Factory Reset). It allows resetting all configurations without deleting your debugging rules.

<img width="372" alt="Screen Shot 2022-06-16 at 19 28 35" src="https://user-images.githubusercontent.com/5878421/174069749-238f8cc6-1ee2-49b2-be93-20874c4a3a30.png">

**Comment by NghiaTranUIT** [comment]
Hey @cameroncooke, sorry for the delay, I finally install the Ventura macOS again on a different disk partition.

The breakpoint issue is fixed on this Beta build: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_3.6.0_Fix_Breakpoint_issue_on_Ventura.dmg

I'm going to fix the toolbar in the next release soon 👍 

### Screenshots 
<img width="1728" alt="Screenshot 2022-06-30 at 20 23 38" src="https://user-images.githubusercontent.com/5878421/176689022-188a6125-e33f-4fa7-879c-4328ac14f0b9.png">

**Comment by cameroncooke** [comment]
Still have the toolbar issue on 3.6.2 on 13.0 Beta (22A5286j)

**Comment by cameroncooke** [comment]
Don't really want to reset all my settings, are you able to reproduce the toolbar overflow bug when icons and labels are enabled before I go down that route?

**Comment by cameroncooke** [comment]
https://user-images.githubusercontent.com/630601/177511392-326a1456-6da5-4304-9af6-b69289214bfd.mov

**Comment by NghiaTranUIT** [comment]
Yes, I can reproduce the toolbar issue on macOS 13 beta. The problem is that we can still not build the project on Xcode 14 (beta 1 & 2) due to the conflict with SPM libraries. I checked Xcode's release note, and there is no workaround.

Thus, no toolbar fix on Proxyman 3.6.2. (Fixed the breakpoint issue since it blocks dev work ✅ )

I'm working on an alternative solution to make it builds on Xcode 14 + macOS 13, then I can fix it 👍 

I will definitely include the fix on the next release 😄 👍

**Comment by NghiaTranUIT** [comment]
Fixed: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_3.6.2_Fix_missing_toolbar_items.dmg

- Toolbar items is missing
- Crash when clicking on the Customize Toolbar

![Screenshot_2022-07-07_at_12_55_25](https://user-images.githubusercontent.com/5878421/177703085-ddcd8aed-13ac-45c8-80ab-a2bb30fce3c4.jpg)

**Comment by Floperoid** [comment]
Hi! I have the same issue. Unfortunately my license expired a while ago. Is there any way to get this fix without renewing a license?

**Comment by NghiaTranUIT** [comment]
> Hi! I have the same issue. Unfortunately my license expired a while ago. Is there any way to get this fix without renewing a license?

You might try to do Factory Reset in the Help -> Advance menu (uncheck the reset user data, or your tools rules are reset). It might fix the bug 🐛

**Comment by Floperoid** [comment]
It didn't help(

**Comment by NghiaTranUIT** [comment]
Hey @Floperoid please email to support@proxyman.io with your license key, we can help you to change the expiry date, so you can get the update 👍

**Comment by Floperoid** [comment]
Thanks!

**Comment by NghiaTranUIT** [comment]
Hey @Floperoid your new expiry license is 1 Jan 2023, which allows you to get the fix update 👍
