### ISSUE TITLE
Allow list isn't always honoured?

### ISSUE THREAD

**Issue by ChrisMash** [ProxymanApp/Proxyman#1711]
## Description

I set my allow list to only two domains and this seemed to be working for filtering traffic from an iOS device connected to my Mac but other traffic on my Mac and simulator, from different domains, was still getting reported in proxyman.

I often have issues with VPN where proxyman is affecting the requests and causing my network to seize up until I reset the vpn and proxyman in a certain order. It seems I need proxyman to just leave alone the requests the vpn is making itself so they don't get affected.

## Steps to Reproduce

1. Setup a specific domain in the allow list
2. Notice that other domains are still reported in proxyman

## Current Behavior

Domains not on the allow list are reported in proxyman 

## Expected Behavior

Only domains on the allow list are touched by proxyman, otherwise they're allowed to silently go through in the background, untouched.

## Environment

- App version: Proxyman 4.8.2
- macOS version: Ventura 13.4.1

**Comment by NghiaTranUIT** [comment]
Hi @ChrisMash Look like the White List doesn't work on the latest build. I'm going to fix it now and send you hotfix build 👍

**Comment by NghiaTranUIT** [comment]
@ChrisMash let's try this Beta build: https://download.proxyman.io/beta/Proxyman_4.8.2_Fix_Allow_List.dmg

The bug is fixed. Sorry for any inconvenience.

**Comment by ChrisMash** [comment]
Thanks for the quick beta! It looks good so far 🤞🏻

**Comment by ChrisMash** [comment]
While it seems to be working mostly I can still see some Firebase requests from the simulator still showing up (not a domain that's in the allow list)
