### ISSUE TITLE
Proxy Helper Tool asking to be installed at each startup

### ISSUE THREAD

**Issue by novitae** [ProxymanApp/Proxyman#1856]
## Description
Each times I open Proxyman, Proxy Helper Tool says New version of Proxy Helper Tool (1.5.0), while I install it each time, and verify it is installed. IT IS VERY VERY ANNOYING !!!

## Steps to Reproduce

1. Open
2. Install it as it is told to be
3. Close
4. Open

## Current Behavior
ASking to be installed

## Expected Behavior
Not asking

## Environment

- App version: 4.14.0

**Comment by NghiaTranUIT** [comment]
@novitae this issued is fixed. You should try this Beta: https://github.com/ProxymanApp/Proxyman/issues/1833#issuecomment-1798117777

The problem is your Macbook has disabled SIP, so Proxyman can't verify the Helper Tool properly.
- Enable the SIP with your current build
- or using the Beta build will fix it

**Comment by NghiaTranUIT** [comment]
I will rollout the official updates soon 👍

**Comment by League2EB** [comment]
@NghiaTranUIT 
This issue still exists, here is my device information and version information.

OS: macOS Sonoma 14.7.1 arm64
Apple M2 Max (12) @ 3.50 GHz
System Integrity Protection status: disabled
ProxyMan installed on: setapp subscription
Proxyman Version 5.16.0 (51600) | macOS: Version 14.7.1 (Build 23H222)

Note: When I just switch tabs, the installation status will change to "not installed".
For some reason, SIP must be "disabled" on my work device.

If this issue occurs in 2023, I believe it should be resolved by 2025.
Is there any solution? Thank you.

https://github.com/user-attachments/assets/3c8bf36b-d77f-4d5b-b611-1f942d101668

**Comment by NghiaTranUIT** [comment]
@League2EB Can you uninstall it first, then re-install it again?

Or you can simply delete it at `/Library/PrivilegedHelperTools/com.proxyman.NSProxy.HelperTool`. Make sure to close the app if you delete this file.

-------
From what I tested in 2023, it works with disabled SIP with normal Proxyman and Setapp version. Not sure if Setapp changes anything under hood.

**Comment by League2EB** [comment]
> [@League2EB](https://github.com/League2EB) Can you uninstall it first, then re-install it again?
> 
> Or you can simply delete it at `/Library/PrivilegedHelperTools/com.proxyman.NSProxy.HelperTool`. Make sure to close the app if you delete this file.
> 
> From what I tested in 2023, it works with disabled SIP with normal Proxyman and Setapp version. Not sure if Setapp changes anything under hood.

When I followed your advice to try the following two methods, the issue still cannot be resolved.

1. Reinstall ProxyMan

2. Delete /Library/PrivilegedHelperTools/com.proxyman.NSProxy.HelperTool

Is there any other way I can provide more information?
Thank you for your reply.
