### ISSUE TITLE
Search params encode issue for Map Remote and Scripting

### ISSUE THREAD

**Issue by JasonBoy** [ProxymanApp/Proxyman#2036]
## Description
I have some api using strapi cms, when I use proxyman to proxy to local strapi host, the query string looks like being changed, especially for the key of the querystring, which should be not be encoded for the target strapi api, the `sort[0]=` should be untouched, but after mapped, it was encoded to `sort%5B0%5D=`, results 400 error; both map remote and scripting has this issue, also one case I encountered before is that when the url has some Chinese directly, it also proxied incorrectly in scripting, hope to take a look

![CleanShot 2024-05-27 at 00 06 35@2x](https://github.com/ProxymanApp/Proxyman/assets/2911620/9abd2936-4558-4f9e-94eb-99b1441243f7)
the left is mapped, the right one is not using map remote:
![CleanShot 2024-05-27 at 00 18 08@2x](https://github.com/ProxymanApp/Proxyman/assets/2911620/5a1bc3f6-e3c8-4fa8-a04c-cdc5c2cfdf81)

## Current Behavior

key of the querystring was encoded

## Expected Behavior

key of the querystring should not be touched

## Environment

- v5.3
- macOS version: e.g macOS Monterey

**Comment by NghiaTranUIT** [comment]
Thanks, let me investigate it on both macOS and Windows 👍

**Comment by NghiaTranUIT** [comment]
@JasonBoy can you check this Beta build: https://download.proxyman.io/beta/Proxyman_5.3.0_Fix_Map_Remoter_with_percent-encoded.dmg

It's fixed with Map Remote.

![Screenshot 2024-05-27 at 1 14 55 PM](https://github.com/ProxymanApp/Proxyman/assets/5878421/7a15ce3b-5823-4c4f-a520-26edbbe06f08)



I'm working on the Scripting.

**Comment by JasonBoy** [comment]
@NghiaTranUIT  I am using scripting, but with latest 5.4, I'am still have this issue:
![CleanShot 2024-05-31 at 17 16 12](https://github.com/ProxymanApp/Proxyman/assets/2911620/a09d3f6f-7a18-46a0-b463-da5eef376717)
![image](https://github.com/ProxymanApp/Proxyman/assets/2911620/2228331a-18dc-4cc0-8f7f-3aa8368bd648)

**Comment by JasonBoy** [comment]
was this fixed only on map remote currently?

**Comment by NghiaTranUIT** [comment]
it's fixed on the Map Remote and Breakpoint.

**Comment by JasonBoy** [comment]
OK, i will try map remote

**Comment by JasonBoy** [comment]
@NghiaTranUIT sorry to bother, after trying the v5.4, I'm still facing the issue, here are some screenshots:
<img width="794" alt="image" src="https://github.com/ProxymanApp/Proxyman/assets/2911620/db39fd4f-a43d-4542-8035-cf48cf84174d">
<img width="689" alt="image" src="https://github.com/ProxymanApp/Proxyman/assets/2911620/7d6f8322-ec67-4233-a1c2-cf71e2471523">

**Comment by NghiaTranUIT** [comment]
@JasonBoy sorry, can you try this Beta build: https://download.proxyman.io/beta/Proxyman_5.4.0_Fix_Percent_encoded_in_Map_Remote_and_Breakpoint.dmg

My mistake is that this fix doesn't include on the latest build : /

**Comment by JasonBoy** [comment]
@NghiaTranUIT This build works, thanks

**Comment by JasonBoy** [comment]
@NghiaTranUIT is this fixed in Scripting tool ?

**Comment by wheeeeel** [comment]
@NghiaTranUIT I have the same issue with Proxyman Version 5.7.0 (50700) | macOS: Version 14.4.1 (Build 23E224). Has it been completely fixed?

<img width="816" alt="image" src="https://github.com/user-attachments/assets/47d5d3f7-483c-45a7-b7b2-b7f3a28f4e41">

```
curl -x http://localhost:8088 http://localhost/get\?a\=test\%2Btest
```

<img width="1554" alt="image" src="https://github.com/user-attachments/assets/30c2e1c3-71f4-4d76-a2d8-06c4411354e4">

**Comment by NghiaTranUIT** [comment]
@wheeeeel from what I tested, it works on 6.6.0 👍
