### ISSUE TITLE
[Feature] Filter by resource type

### ISSUE THREAD

**Issue by neofight** [ProxymanApp/Proxyman#263]
It would be great to be able to quickly filter by resource type as in the Safari inspector. Usually I don't want to see all the image requests for example.

![image](https://user-images.githubusercontent.com/221644/63698022-514bb180-c81e-11e9-8483-208f6d8b2198.png)

**Comment by shirshak55** [comment]
yea and most of the time I just want to totally exclude image, font etc. :(

**Comment by NghiaTranUIT** [comment]
Related to #251 and #164. 

I guess I could quickly support the "filter" by introducing the lightweight By-Pass list (wildcard support). Thus, *.jpg or whatever you like could be ignore in entire Proxyman, and less distraction 😄

If you like it, I could push it forward in Proxyman 1.6.0 (next release)

**Comment by neofight** [comment]
While obviously the linked features offer a lot of power, what’s needed is a quick way to cover what must be a common scenario, rather than having to configure from scratch. So whatever mechanism is used, including wildcards, some default presets would be the way to go. Filtering on mime type would seem to be what’s needed.

Obviously the sooner you can implement the better as far as I am concerned 😉

**Comment by NghiaTranUIT** [comment]
Agree with you @neofight. I would ship the MVP version of smart folder as a simple Filter (like Safari) on specific Folder for you as a simple needed.

For instance,
- Right click on Folder, Domain, Node -> Filter Menu -> Select the filter type (it could be All | APIs | Image | .... ).

I will ship it in next version 👍

**Comment by NghiaTranUIT** [comment]
The feature is done. I'm going to release soon 🥇

**Comment by shirshak55** [comment]
wow will wait for it to test it

**Comment by NghiaTranUIT** [comment]
All done 👍 

## 🤯 Changelogs 
- [x] Introduce Filter Panel on top of Flow List (CMD+F)
- [x] Able to filter by URL or Content Type
- [x] Work with sorting
- [x] Support selection label in bottom of Toolbar

<img width="1161" alt="Screen Shot 2019-09-04 at 23 22 13" src="https://user-images.githubusercontent.com/5878421/64273199-055de280-cf6b-11e9-86f1-0117e5f2185a.png">

**Comment by NghiaTranUIT** [comment]
Hey @shirshak55 @neofight , let check the Filter BETA at https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_1.5.1_Filter.dmg

I would release tmr if everything is good. 👍

**Comment by neofight** [comment]
A few quick observations:

* 404 images always get classified as a document (because the returned mime type to text/html)
* Ajax requests end up in the document tab rather than the XHR tab
* A have an SVG which is returned from the server without a mime type so it gets classified as a document.
* JS & CSS should have their own tabs

Maybe worth looking at the accept header of the request to help determine the file type? E.g.

<img width="308" alt="CleanShot 2019-09-04 at 18 52 37@2x" src="https://user-images.githubusercontent.com/221644/64275152-375c4e00-cf45-11e9-8bd1-a35ae8b4927b.png">

**Comment by NghiaTranUIT** [comment]
Thank for quick feedback @neofight. I'd take the accept header to determine which group should be. Other issues are correct and will be fix before releasing.

However, the concern is that It's possible to detect the Ajax requests since Proxyman is just MiTM, not Google Chrome, who know where the requests are from. Currently, all JSON, XML, www-form are belonging to XHR tab, and it seems to be incorrect, since other requests (maybe text/) could be too.

I guess I should remove the XHR tab and introduce JSON, XML, FORM, JS and CSS tab.

**Comment by neofight** [comment]
Regarding XHR I suspect you are right, so I agree it's probably best to remove the tab. Personally I'd just have JSON, XML, FORM under the document tab rather than create new ones. Generally as a web developer I want to separate out pages / dynamic content from all the static resources such as images, css etc.

**Comment by NghiaTranUIT** [comment]
From your feedback, I've fixed and released new version of Global Filter bar @neofight at https://github.com/ProxymanApp/Proxyman/releases/tag/1.6.0

You can update directly from the app. Let check it out 😄

**Comment by neofight** [comment]
Looks nice, one issue still remains (again should be resolvable by looking at file extension / accept headers):

* When an image url returns 404 it gets classified as a document (because the returned mime type to text/html)

Also, this is a bit nit picky I know, but I don't like "Doc" and "Img" as a tab names, maybe just use the full words?

**Comment by NghiaTranUIT** [comment]
I deliberately make the label shorter since it could take less space to present entire filter bar. 
I will double check the 404-case and make the title is full since it makes more sense 👍

**Comment by shirshak55** [comment]
Yea short is nice by the way. Anyway we can add advance filters in left
side so user can name their filter anyway in future :)
