### ISSUE TITLE
[BUG] IP v4 is not correct for Remote Device

### ISSUE THREAD

**Issue by NghiaTranUIT** [ProxymanApp/Proxyman#520]
### Description
For some reason, the logic to detect the current IP v4 is not correct. It presents the different one.

A user helps us to reproduce it. The code returns two IPs and the first one is not correct.

```
["fe80::aede:48ff:fe00:1122%en5", "fe80::149d:ede:c70c:ae38%en7", "169.254.100.79", "fe80::52de:86dd:62dd%en0", "192.168.1.103", "2a02:1206:45a8:4bc0:66:8d84:c69b:f524", "2a02:1206:45a8:4bc0:9890:1986:89f:8abe", "fe80::106c:18ff:fe84:c44e%awdl0", "fe80::106c:18ff:fe84:c44e%llw0", "fe80::f271:6741:d751:358a%utun0", "fe80::d2c4:8e44:af5b:b3ab%utun1"]
```

We should fix it

### Acceptance Criteria
- Improve to code to get the local IP (192.*) rather than returing the first v4

**Comment by NghiaTranUIT** [comment]
Fixed 🤚 https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_2.0.1_Fix_IP_Address.dmg

**Comment by crankygeek** [comment]
@NghiaTranUIT Using Version 2.1.0 (20100), I'm still seeing the 169.* addresses for my remote devices (iPads). Should that no longer be the case, or am I misunderstanding the purpose of this issue?

(I actually came here to add a suggesting for combining clients into folders for this reason, as well as iPv6 addresses. I can still file that separately if you think it's worth considering.)

**Comment by NghiaTranUIT** [comment]
Hi @crankygeek, please Hold the Option Key and Click on the Wifi icon (System Menu Bar), and see what the IP Address is. Is it the same with `162.*` ?

If it's the same, it's correct behavior because there is no `192.*`, Proxyman will return the possible values.
If there is `192.*` IP, I will return it because it's likely the correct IP that the Remove Device can connect

The problem is that there is no reliable way to get extract IP address from current Wifi, so Proxyman will receive all available IPs and figure it out which one is right 😄

**Comment by NghiaTranUIT** [comment]
> actually came here to add a suggesting for combining clients into folders for this reason, as well as iPv6 addresses?

Can you elaborate? I'm not sure if I understand 🤔

**Comment by crankygeek** [comment]
@NghiaTranUIT Sure!

I typically have 3-5 iPads proxying through my Mac. For whatever reasons, each one may show up under multiple addresses in Proxyman. For example:
- 192.168.0.1
- 169.254.45.108
- (IPv6 address)

These are all three the same device, but they are listed as three separate remote devices. Add additional devices and the list becomes a lot to manage. I was really happy to see Device Nicknames get added, and it helps a bit, but any particular session may send traffic to any of the IP addresses, so it's not possible to select one to observe all traffic. I was thinking that adding a device folder, similar to a Pin folder, could help. I could assign all the various IPs for a particular device to a folder, then select that folder to view all traffic for that device.

**Comment by crankygeek** [comment]
@NghiaTranUIT Was that description helpful?

**Comment by NghiaTranUIT** [comment]
I understand your situation. Looks like it's a bug because the same device creates 3 different IP Folders => It should be only one.

On the other hand, the idea about the `Device Folder`, to show all traffic from all devices is reasonable. I will consider to support it in the next release 👍

**Comment by crankygeek** [comment]
Small clarification for my request - I'd like to be able to group devices into individual folders (assuming multiple IPs keep happening), e.g.:
- iPad 1 (folder)
  - IP 1 (device)
  - IP 2 (device)
- iPad 2 (folder)
  - IP 3 (device)
  - IP 4 (device)

**Comment by crankygeek** [comment]
Hi @NghiaTranUIT 

I was just chatting with @mprice-banno about 169. addresses still showing up in the device list (using Version 2.16.0 (21600)).

He discovered that the IP is only included if the device is tethered to the Mac while proxying. That probably explains why I saw this after your earlier fix, because I mainly only use my devices while tethered.

Comparing with the info provided by the user who you mentioned in the issue description, is that perhaps a different case that isn't being accounted for?

I've attached a .zip file an example request log, as well as the output from `ifconfig` with just the 169 interface info, in case it's helpful.

[169-network-stuff.zip](https://github.com/ProxymanApp/Proxyman/files/5817384/169-network-stuff.zip)

Thanks!

- Jack

**Comment by NghiaTranUIT** [comment]
Thanks for the detailed report @crankygeek . Let me try to reproduce it on my end and see if I can fix it 👍
