### ISSUE TITLE
[BUG] Unknown client

### ISSUE THREAD

**Issue by NghiaTranUIT** [ProxymanApp/Proxyman#532]
### Description
Sometime, Proxyman couldn't find the client and it results in the Unknown. Technically, it happens because we find the client too later after the client port is closed -> Thus, it doesn't exist in the IP Table anymore.

We should fix it.

### Acceptance Criteria
- No Unknown Client

**Comment by NghiaTranUIT** [comment]
Fixed: https://s3.console.aws.amazon.com/s3/object/proxyman/beta/Proxyman_2.0.1_Fix_Unknown_Client.dmg?region=us-east-2&tab=overview

**Comment by juliandesmarais** [comment]
@NghiaTranUIT I'm on the latest version and this is still occurring. What logs can I provide?

**Comment by NghiaTranUIT** [comment]
This bug has not been resolved yet. @juliandesmarais Do you know where the traffic comes from? Is it from your app, iOS app, Website, or any known service?

Proxyman might not find a client if it's a low-level system library.

**Comment by NghiaTranUIT** [comment]
@juliandesmarais Just wondering: what is your iOS Simulator version 🤔 

If you don't mind, please print this code:
```swift
    func getDocumentsDirectory() -> URL {
        let paths = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)
        let documentsDirectory = paths[0]
        return documentsDirectory
    }
```
I would like to see the path of your App on the Simulator. It's easier for me to investigate the bug 👍
