### ISSUE TITLE
Wildcard domains not capturing as expected.

### ISSUE THREAD

**Issue by donileo** [ProxymanApp/Proxyman#793]
### Proxyman version? (Ex. Proxyman 1.4.3)
Proxyman Version 2.18.0 (21800)

### macOS Version? (Ex. mac 10.14)
macOS 11.2.1 (20D74)

### Steps to reproduce 
1. Add `cloudfunctions.net` Wildcard to SSL Proxy List - you will see that `cloudfunctions.net*` gets added....
2. Add `cloudfunctions.net` Wildcard to Allow White List, make sure `Include all Subpaths of this url` is checked.
3. Curl the following and notice Proxyman does not capture the result.:

```
curl "https://us-central1-test.cloudfunctions.net/sendLogTest"
```

4. Remove the `cloudfunctions.net*` Wildcard entry from SSL Proxy List and add `*.cloudfunctions.net*`.
5. Modify the `cloudfunctions.net` Wildcard entry from Allow List to be `*.cloudfunctions.net*`.
6. Perform step 3 again and notice the request is now captured.

### Expected behavior
Proxyman should capture the request when entering SSL Proxy List and Allow List Wildcard domain to be `cloudfunctions.net` result without having to add `*.cloudfunction.net*` as a Wildcard which will work. Entering that is pretty much entering a Regex, the user expects that `cloudfunction.net` for both SSL Proxy List and Allow white list should capture this scenario.

**Comment by NghiaTranUIT** [comment]
@donileo I suppose that if we want to:
- Match all sub-domain, we should use `*.cloudfunction.net` (One asterisk(*) and Include all subpath is checked)

> the user expects that cloudfunction.net for both SSL Proxy List and Allow white list should capture this scenario.

I don't think that `cloudfunction.net` should match sub-domains too, because they're different.

> Regarding `*.cloudfunctions.net*`

It might be a bug, I will check it out 👍

**Comment by donileo** [comment]
@NghiaTranUIT I actually forgot to mention above that using `*.cloudfunctions.net` for SSL Proxy List and Allow list also doesn't capture the curl request. It has to be `*.cloudfunctions.net*`. 

When you add `*.cloudfunctions.net` to SSL Proxy List it automatically becomes `*.cloudfunctions.net*` which seems like a separate bug.

**Comment by NghiaTranUIT** [comment]
>  I actually forgot to mention above that using *.cloudfunctions.net for SSL Proxy List and Allow list also doesn't capture the curl request. It has to be *.cloudfunctions.net*.

It might be a bug. I'm investigating it and send you a beta build soon 👍

**Comment by NghiaTranUIT** [comment]
Sorry for the delay, I'm so busy working on other tickets for the 2.19.0 release (https://github.com/ProxymanApp/Proxyman/milestone/102)

> When you add *.cloudfunctions.net to SSL Proxy List it automatically becomes *.cloudfunctions.net* which seems like a separate bug? Maybe not.

It's not a bug. We intentionally add the * to the end to make sure all subpaths of this domain are matched. Many people forget the append the trailing *, so Proxyman could not enable SSL Proxying.

Solution => For the wildcard domain, I present the prefix to make it clear that it's a wildcard. For instance, Wildcard: `*.cloudfunctions.net*`

> Regarding `*.cloudfunctions.net` and "Include all subpath" is ON that not match the curl

It's a bug. I'm working on it now 👍

**Comment by NghiaTranUIT** [comment]
Hey @donileo Let check out this Beta build: https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_2.18.0_Fix_Wildcard.dmg

From now, `*.cloudfunctions.net*` in SSL Proxying and `*.cloudfunctions.net` with "ON Include Subpath" on Whitelist will match your cURL.

<img width="866" alt="Screen Shot 2021-03-05 at 16 37 05" src="https://user-images.githubusercontent.com/5878421/110099112-85b90a00-7dd3-11eb-9357-adc8484215ca.png">

<img width="1593" alt="Screen Shot 2021-03-05 at 16 37 18" src="https://user-images.githubusercontent.com/5878421/110099131-8a7dbe00-7dd3-11eb-8fec-aa2e6848da29.png">

**Comment by donileo** [comment]
Hi @NghiaTranUIT I have tested and believed the issue is now fixed. I am however seeing something new which is that when selecting to add the Wildcard To Allowlist and checking the Allow all Subpaths option back in SSL Proxy List a new entry gets added. I don't believe that’s normal as I should only see the items that I have added in SSL Proxy List. Below is a screenshot of what gets added.
<img width="1172" alt="Screen Shot 2021-03-06 at 11 07 56 AM" src="https://user-images.githubusercontent.com/1881038/110213332-91f1a580-7e6d-11eb-805a-91008ab38d06.png">

**Comment by NghiaTranUIT** [comment]
It's our decision to help people resolves their common mistakes:

Many Proxyman users didn't know that they have to enable SSL on a domain that they added to Block List / Allow List / Other tools. As a result, we've received a lot of questions about why the Block/Allow List doesn't work after adding a new rule.

The answer is quite simple. Just add a domain (in Block/Allow list) to SSL Proxying List or right-click on them -> Enable SSL Proxying.

To make it easier to use, we decide to automatically create a rule in SSL Proxying as soon as new rules are added in debugging tools. 

------------------

From your case, it looks like a bug, because `*.cloudfunction.net` is a wildcard, but it appears as a domain. I will fix it 👍

**Comment by anggrayudi** [comment]
Any updates on this @NghiaTranUIT ?

**Comment by NghiaTranUIT** [comment]
@anggrayudi this bug is already fixed.

If it's not, can you share how to reproduce it? What is your URL, and the wildcard domain ?

**Comment by anggrayudi** [comment]
Hi @NghiaTranUIT — not fixed, I can still reproduce this.

**Proxyman**: 6.12.0 (61200)
**macOS**: 26.5.1 (25F80)

**Setup**: SSL Proxying → Include List has a wildcard entry for our API domain (`*.gopayapi.com`), shown as checked/enabled. No separate Allow/Block List rules are active — just plain SSL Proxying.

**Repro** (isolated with curl through the Proxyman proxy, no app involved):

```
curl --proxy http://127.0.0.1:9090 -k https://customer.staging.gopayapi.com/
```

1. With only the wildcard `*.gopayapi.com` in the Include List (no literal `customer.staging.gopayapi.com` entry), curl still gets a response from the origin — but the request never shows up as a decrypted flow in Proxyman, only a bare `CONNECT` tunnel with empty request/response headers. Querying the flow, `isIntercepted` is `false`, even though the wildcard entry is checked/enabled in the list.
2. I also tried the "fixed" wildcard syntax from earlier in this thread, `*.gopayapi.com*` (leading **and** trailing asterisk) — same result: `isIntercepted: false`, still just a `CONNECT` entry, nothing decrypted.
3. Adding the exact literal subdomain `customer.staging.gopayapi.com` to the Include List and re-running the identical curl command immediately produces a fully decrypted `GET` flow with `isIntercepted: true`, real response headers and body.

Ran this 3x for each configuration to rule out flakiness — 100% consistent both ways. Also reproduced on a second, deeper subdomain (`onekyc.ky.id.staging.gopayapi.com`, 4 labels), so it isn't limited to single-level subdomains either.

So: wildcard entries (`*.domain.com` or `*.domain.com*`) display as enabled in the SSL Proxying list, but never actually trigger interception — only an exact, fully-qualified domain entry does.

This is exactly what originally sent us down this path: our Flutter app's HTTPS calls to a wildcarded API domain came back empty/uninspectable in Proxyman until we replaced the wildcard with the fully-qualified subdomain in the SSL Proxying list. This curl-only repro isolates the same behavior down to the wildcard matching/interception logic itself, independent of the app.

**Comment by NghiaTranUIT** [comment]
@anggrayudi I tested on Proxyman macOS 6.12.0 and it works fine 🤔 See the below video.

I think you should go to Tools menu -> SSL Proxying List -> Exclude List and see if there are any entries which conflicts with `*.gopayapi.com` ? Delete all entries in the Exclude List can fix it.


https://github.com/user-attachments/assets/81520d1a-39de-40e9-8aee-00e1e3f07ede

**Comment by anggrayudi** [comment]
As you can see @NghiaTranUIT , it stucks in `CONNECT` state:

<img width="1728" height="1117" alt="Image" src="https://github.com/user-attachments/assets/5dc43ecb-8e38-4215-816d-297cc75ed85f" />

But when I add the full subdomain, it works:

<img width="1728" height="1117" alt="Image" src="https://github.com/user-attachments/assets/0906caab-356f-46e9-9399-54451000cfa9" />

I tried `*.gopayapi.com` with Charles Proxy and it works.

Can you try deep analysis with Fable 5 or Opus 4.8 to verify this issue?

**Comment by NghiaTranUIT** [comment]
@anggrayudi can you open the Exclude List Tab in the SSL Proxying List Windows?

Try to remove all entries in the Exclude List

<img width="1416" height="902" alt="Image" src="https://github.com/user-attachments/assets/8c65d168-fd5a-4a7b-b9d8-83bacfd87c88" />

**Comment by anggrayudi** [comment]
I have no exclude list item since the first place @NghiaTranUIT :

<img width="1728" height="1117" alt="Image" src="https://github.com/user-attachments/assets/3057ec81-458c-4afa-80ae-11fc8d717416" />

**Comment by NghiaTranUIT** [comment]
@anggrayudi Ok see. The problem is your Entry is not a Wildcard. See below image, it shows `Wildcard: *.gopayapi.com`. Your entry is `*.gopayapi.com`.

How do you create this entry? I think you should create it by clicking on the + button -> Add domains -> Enter your *.gopayapi.com ?

<img width="458" height="298" alt="Image" src="https://github.com/user-attachments/assets/3460e969-0003-4e3e-bcb3-7908f015df02" />

**Comment by NghiaTranUIT** [comment]
If you create or edit an Entry, Proxyman will automatically detect if the domain has any wildcard characters, such as * and ? and it will create a wildcard entry for you. 

Not sure how can you create `*.gopayapi.com` without the wildcard mark?

**Comment by anggrayudi** [comment]
Use AI MCP @NghiaTranUIT , this is my prompt:
```
Activate proxyman to current active android emulator and add *.gopayapi.com into included list.
```
If I use GUI, I can verify we have `Wildcard` here:

<img width="627" height="271" alt="Image" src="https://github.com/user-attachments/assets/3e8e7cb5-ebf6-4220-a215-de1801e51b65" />

**Comment by NghiaTranUIT** [comment]
ok, I will fix now 👍 The MCP should create a wildcard entry if it's a wildcard

**Comment by NghiaTranUIT** [comment]
@anggrayudi it's fixed: https://assets.proxyman.com/beta/Proxyman_6.12.0_Fix_MCP_when_creating_new_ssl_entry.dmg

- MCP will create a correct SSL Entry if it's a wildcard 👍

**Comment by anggrayudi** [comment]
Cool, I tested and it is fixed now. Thanks @NghiaTranUIT . We can close this issue IMO.

**Comment by anggrayudi** [comment]
Another issue I observe when using GUI with full screen is this @NghiaTranUIT :

https://github.com/user-attachments/assets/3d4617c2-6ce2-4808-b1b1-5c905c894634

It opens a new screen, instead of showing it as a dialog on top of the current Proxyman active window.
